spring:
  application:
    name: "@project.artifactId@"
    description: "@project.name@"
  build:
    version: "@project.version@"
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/platform
    username: postgresql
    hikari:
      pool-name: hikari-platform-service-platform
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  flyway:
    # clean-on-validation-error: true
    baseline-on-migrate: true
    ignore-missing-migrations: true
    # enabled: false
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${port:8000}
  rest:
    base: null
management:
  endpoints:
    jmx:
      exposure:
        include: health,info,prometheus
    web:
      base-path: /admin
      exposure:
        include: health,info,prometheus
  info:
    git:
      mode: full
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  servers:
    - url: http://localhost:8000
      description: localhost

app:
  auth:
    rbac:
      enabled: true
      jwt:
        secret: 123456
  core:
    plugin:
      enabled: false
    backend:
      url: dev.core.consoleconnect.com
      url2: dev.consolecore.io
      token: ${CONSOLE_CORE_AGENT_TOKEN}
      env: LOCAL 
logging:
  level:
    com.pccw.platform.service: DEBUG